const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>Array.from(c.querySelectorAll(s));
$('#year')&&($('#year').textContent=new Date().getFullYear());

const navToggle=$('.nav-toggle');const overlay=document.querySelector('[data-overlay]');
function setMenu(open){const expanded=!!open;navToggle&&navToggle.setAttribute('aria-expanded',expanded);overlay&&(overlay.hidden=!expanded);document.body.style.overflow=expanded?'hidden':'';$$('.nav-link').forEach(a=>a.style.display=expanded?'block':'');}
navToggle&&navToggle.addEventListener('click',()=>setMenu(navToggle.getAttribute('aria-expanded')!=='true'));overlay&&overlay.addEventListener('click',()=>setMenu(false));

$$('[data-dropdown]').forEach(dd=>{const btn=$('.dropdown-toggle',dd);if(!btn)return;btn.addEventListener('click',e=>{e.preventDefault();dd.classList.toggle('open');btn.setAttribute('aria-expanded',dd.classList.contains('open'));});dd.addEventListener('mouseleave',()=>{dd.classList.remove('open');btn.setAttribute('aria-expanded','false');});});

(function(){const wrap=$('#slides');if(!wrap) return;const slides=$$('.slide',wrap);const left=$('.arrow-left');const right=$('.arrow-right');const currentEl=$('#heroCurrent');const totalEl=$('#heroTotal');let index=0;const total=slides.length;const pad2=n=>String(n).padStart(2,'0');totalEl.textContent=pad2(total);function show(i){slides[index].classList.remove('is-active');index=(i+total)%total;slides[index].classList.add('is-active');currentEl.textContent=pad2(index+1);}left.addEventListener('click',()=>show(index-1));right.addEventListener('click',()=>show(index+1));document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')show(index-1);if(e.key==='ArrowRight')show(index+1);if(e.key==='Escape')setMenu(false);});let auto=setInterval(()=>show(index+1),5500);const hero=$('.hero-carousel');function pause(){clearInterval(auto);}function resume(){auto=setInterval(()=>show(index+1),5500);}hero.addEventListener('mouseenter',pause);hero.addEventListener('mouseleave',resume);let x0=null;wrap.addEventListener('touchstart',e=>x0=e.touches[0].clientX,{passive:true});wrap.addEventListener('touchend',e=>{if(x0===null)return;const dx=e.changedTouches[0].clientX-x0;x0=null;if(Math.abs(dx)>40){dx>0?show(index-1):show(index+1);}});})();

(function(){const whats=document.getElementById('whatsappCta');if(!whats)return;const url=new URL(whats.href);url.searchParams.set('utm_source','site');url.searchParams.set('utm_medium','cta');url.searchParams.set('utm_campaign','whatsapp');whats.href=url.toString();})();

(function(){const form=document.getElementById('contactForm');const note=document.getElementById('formNote');if(!form)return;form.addEventListener('submit',e=>{const hp=form.querySelector('[name="_honeypot"]').value;if(hp){e.preventDefault();return;}if(!form.checkValidity()){e.preventDefault();note.textContent='Preencha os campos obrigatórios.';return;}note.textContent='Enviando…';});})();

let lightboxEl=null;function ensureLightbox(){if(lightboxEl)return lightboxEl;lightboxEl=document.createElement('div');lightboxEl.className='lightbox';lightboxEl.setAttribute('hidden','');lightboxEl.innerHTML=`<button aria-label="Fechar">✕</button><img alt="Foto ampliada" />`;document.body.appendChild(lightboxEl);lightboxEl.addEventListener('click',e=>{if(e.target.tagName!=='IMG')closeLightbox();});lightboxEl.querySelector('button').addEventListener('click',closeLightbox);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox();});return lightboxEl;}
function openLightbox(src,alt){const lb=ensureLightbox();const img=lb.querySelector('img');img.src=src;img.alt=alt||'Foto ampliada';lb.removeAttribute('hidden');document.body.style.overflow='hidden';}
function closeLightbox(){if(!lightboxEl)return;lightboxEl.setAttribute('hidden','');document.body.style.overflow='';}
$$('.masonry').forEach(gal=>{gal.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();openLightbox(a.getAttribute('href'),a.querySelector('img')?.alt);});});

(function(){const els=$$('.reveal');if(!('IntersectionObserver'in window)||!els.length){els.forEach(el=>el.classList.add('visible'));return;}const io=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');io.unobserve(entry.target);}})},{threshold:0.16});els.forEach(el=>io.observe(el));})();